# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: marcell.nagy@diamond.ac.uk
author_name: Marcell Nagy
component_owner: group:default/sscc
description: FastCS support for the ThorLabs MFF (Motorized Filter Flipper)
distribution_name: thorlabs-mff-fastcs
docker: true
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: thorlabs_mff_fastcs
pypi: true
repo_name: thorlabs-mff-fastcs
type_checker: mypy
